openapi: 3.0.0
info:
  version: 1.0
  title: KIP-7 API
  description: "# Introduction\nKIP-7 API is a RESTful API for managing KIP-7 contracts\
    \ and tokens that follow the [KIP-7 Fungible Token Standard](https://kips.klaytn.com/KIPs/kip-7).\
    \  \nYou can deploy contracts and send tokens using the default contract managing\
    \ account (`deployer`) and an `alias`. And by using SDK like caver, \nyou can\
    \ manage your contracts and tokens using [Wallet API](https://refs.klaytnapi.com/en/wallet/latest)\
    \ for contracts created on the Klaytn Network.\n\n\n\n# Error Codes\n\n## 400:\
    \ Bad Request\n\n| Code | Messages |\n| --- | --- |\n| 1130050 | incorrect request;\
    \ spender |\n| 1130107 | incorrect bookmark |\n| 1134410 | invalid address; to</br>invalid\
    \ address; owner</br>invalid address; address |\n| 1134411 | invalid amount; amount\
    \ |\n\n## 404: Not Found\n\n| Code | Messages |\n| --- | --- |\n| 1134504 | contract\
    \ not found |\n| 1134506 | deployer not found |\n\n## 409: Conflict\n\n | Code\
    \ | Messages | \n | --- | --- | \n | 1134900 | duplicate alias\n1134902 | contract\
    \ already paused\n1134903 | contract already unpaused | \n"
servers:
- url: https://kip7-api.klaytnapi.com
security:
- basic: []
paths:
  /v1/contract:
    get:
      tags:
      - KIP7
      summary: Retrieves a list of KIP-7 contracts
      description: "Retrieves a list of all KIP-7 contracts deployed by the user.\
        \ The contracts will be listed in descending order of transactions requested\
        \ for creation.<p></p>\n\nThe `status` field in the response has one of the\
        \ following values.<p></p>\n\n- `init`: The initial status before sending\
        \ the transaction\n- `submitted`: The status of having submitted the contract\
        \ deploy transaction\n- `deployed`: The status of having deployed the contract<p></p>\n\
        \n"
      operationId: ListContractsInDeployerPool
      parameters:
      - name: x-chain-id
        in: header
        description: Klaytn Network Chain ID (1001 or 8217)
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: size
        in: query
        description: The maximum number of items to return
        required: false
        style: form
        explode: true
        schema:
          type: string
        example: ""
      - name: cursor
        in: query
        description: Offset for the first item. You can query data after the given
          offset using the `cursor` value returned in the response.
        required: false
        style: form
        explode: true
        schema:
          type: string
        example: ""
      - name: status
        in: query
        description: "You can only choose one deploy status [`all`,`init`,`submitted`,`deployed`]\
          \ for the contract you wish to query. The default value is `all`."
        required: false
        style: form
        explode: true
        schema:
          type: string
        example: ""
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Kip7ContractListResponse'
              examples:
                Success:
                  summary: Success
                  value:
                    items:
                    - address: 0x0f73bb170deb398180f02e60d7ea154c270b8fb9
                      alias: mycontract
                      decimals: 8
                      name: MyKIP7
                      status: deployed
                      symbol: MSK7
                      totalSupply: 0x500
                    cursor: ""
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Bad Request - invalid bookmark:
                  summary: Bad Request - invalid bookmark
                  value:
                    code: 1130107
                    message: incorrect bookmark
    post:
      tags:
      - KIP7
      summary: Deploy KIP-7 contract
      description: "Deploys a standard KIP-7 contract based on the data provided.\
        \ The contract will be deployed via the default contract management account.\
        \ You cannot change the deployer.  \nYou can retrieve the default contract\
        \ management accounts via [/v1/deployer/default](#operation/GetDefaultDeployer).\
        \  \nYour `alias` must only contain lowercase alphabets, numbers and hyphens\
        \ and begin with an alphabet. <p></p>\n\n"
      operationId: DeployContract
      parameters:
      - name: x-chain-id
        in: header
        description: Klaytn Network Chain ID (1001 or 8217)
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/DeployKip7ContractRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Kip7TransactionStatusResponse'
              examples:
                Success:
                  summary: Success
                  value:
                    status: Submitted
                    transactionHash: 0xf7843f034f2283d0ec32886a69d44a85ce19af25d8bd89d84322b973a86328a8
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Duplicate Alias:
                  summary: Duplicate Alias
                  value:
                    code: 1134900
                    message: duplicate alias
  /v1/contract/{contract-address-or-alias}:
    get:
      tags:
      - KIP7
      summary: Get KIP-7 contract data
      description: |+
        Returns contract data of the given alias or contract address. <p></p>

      operationId: GetContract
      parameters:
      - name: x-chain-id
        in: header
        description: Klaytn Network Chain ID (1001 or 8217)
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: contract-address-or-alias
        in: path
        description: Contract address (in hexadecimal with the 0x prefix) or an alias
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Kip7ContractMetadataResponse'
              examples:
                Success:
                  summary: Success
                  value:
                    address: 0x0f73bb170deb398180f02e60d7ea154c270b8fb9
                    decimals: 8
                    name: MyKIP7
                    symbol: MSK7
                    totalSupply: 0x500
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Not Found - alias:
                  summary: Alias not found
                  value:
                    code: 1134504
                    message: contract not found
  /v1/contract/{contract-address-or-alias}/pause:
    post:
      tags:
      - KIP7
      summary: Pause KIP-7 contract
      description: "Pauses all token transfers and validations for a given contract.\
        \ \nYou can resume token transfers by using [/v1/{contract-address-or-alias}/unpause](#operation/UnpauseContract).<p></p>\n\
        \n"
      operationId: PauseContract
      parameters:
      - name: x-chain-id
        in: header
        description: Klaytn Network Chain ID (1001 or 8217)
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: contract-address-or-alias
        in: path
        description: Contract address (in hexadecimal with the 0x prefix) or an alias
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Kip7TransactionStatusResponse'
              examples:
                Success:
                  summary: Success
                  value:
                    status: Submitted
                    transactionHash: 0xf7843f034f2283d0ec32886a69d44a85ce19af25d8bd89d84322b973a86328a8
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Not Found - alias:
                  summary: Alias not found
                  value:
                    code: 1134504
                    message: contract not found
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Conflict - paused:
                  summary: Conflict - paused
                  value:
                    code: 1134902
                    message: contract already paused
  /v1/contract/{contract-address-or-alias}/unpause:
    post:
      tags:
      - KIP7
      summary: Resume KIP-7 contract
      description: |+
        Resumes token transfers and validations for a given contract.<p></p>

      operationId: UnpauseContract
      parameters:
      - name: x-chain-id
        in: header
        description: Klaytn Network Chain ID (1001 or 8217)
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: contract-address-or-alias
        in: path
        description: Contract address (in hexadecimal with the 0x prefix) or an alias
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Kip7TransactionStatusResponse'
              examples:
                Success:
                  summary: Success
                  value:
                    status: Submitted
                    transactionHash: 0xf7843f034f2283d0ec32886a69d44a85ce19af25d8bd89d84322b973a86328a8
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Not Found - alias:
                  summary: Alias not found
                  value:
                    code: 1134504
                    message: contract not found
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Conflict - unpaused:
                  summary: Conflict - unpaused
                  value:
                    code: 1134903
                    message: contract already unpaused
  /v1/contract/{contract-address-or-alias}/mint:
    post:
      tags:
      - KIP7
      summary: Mint KIP-7 tokens
      description: "Mints a new token for a given user.  \nThe total supply in the\
        \ contract (`totalSupply`) will increase as requested.<p></p>\n\n"
      operationId: MintToken
      parameters:
      - name: x-chain-id
        in: header
        description: Klaytn Network Chain ID (1001 or 8217)
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: contract-address-or-alias
        in: path
        description: Contract address (in hexadecimal with the 0x prefix) or alias
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/MintKip7TokenRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Kip7TransactionStatusResponse'
              examples:
                Success:
                  summary: Success
                  value:
                    status: Submitted
                    transactionHash: 0x31dd75c39e569b3fa5336186a6a464c0a84c487f481e80009a4d238fbe0d2357
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Bad Request - invalid address:
                  summary: Bad Request - invalid address
                  value:
                    code: 1134410
                    message: invalid address; to
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Not Found - alias:
                  summary: Alias not found
                  value:
                    code: 1134504
                    message: contract not found
  /v1/contract/{contract-address-or-alias}/transfer:
    post:
      tags:
      - KIP7
      summary: KIP-7 token transfer
      description: "Sends tokens of the contract. \nIf `from` is not specified in\
        \ the request, the sender will be the `deployer` of the contract.  <p></p>\n\
        \n**Note**: This API requires two types of x-krn, separated by `,` in the\
        \ request header. <br>\nkrn:{chain-id}:kip7:{account-id}:account-pool:default,krn:{chain-id}:wallet:{account-id}:account-pool:{pool-name}<p></p>\n\
        \n- The first KRN: Default KIP-7 `account-pool`\n- The second KRN: Wallet\
        \ API `account-pool`, which has the `from` account\n- Just as in other APIs,\
        \ omitting the x-krn will give it the default value.<p></p>\n\n"
      operationId: TransferToken
      parameters:
      - name: x-chain-id
        in: header
        description: Klaytn Network Chain ID (1001 or 8217)
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: contract-address-or-alias
        in: path
        description: Contract address (in hexadecimal with the 0x prefix) or an alias
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/TransferKip7TokenRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Kip7TransactionStatusResponse'
              examples:
                Success:
                  summary: Success
                  value:
                    status: Submitted
                    transactionHash: 0x60412f876bfb8ae9953caa47be11cd5961a591198e09c25bb8cc3b26e416a862
                Success with multisig account:
                  summary: Success with multisig account
                  value:
                    status: Pending
                    transactionId: 0x947e5149c93e0bdbd3973e348a4b3557b857d2dee865f407b29f7f02c9b5d22e
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Bad Request - invalid address:
                  summary: Bad Request - invalid address
                  value:
                    code: 1134410
                    message: invalid address; to
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Not Found - alias:
                  summary: Alias not found
                  value:
                    code: 1134504
                    message: contract not found
  /v1/contract/{contract-address-or-alias}/transfer-from:
    post:
      tags:
      - KIP7
      summary: Delegated KIP-7 token transfer
      description: "Sends tokens on behalf of the owner. \nYou need to approve token\
        \ transfers in advance ([/v1/{contract-address-or-alias}/approve](#operation/ApproveToken)).\
        \  <p></p>\n\n**Note**: This API requires two types of x-krn, separated by\
        \ `,` in the request header. <br>\nkrn:{chain-id}:kip7:{account-id}:account-pool:default,krn:{chain-id}:wallet:{account-id}:account-pool:{pool-name}<p></p>\n\
        \n- The first KRN: Default KIP-7 `account-pool`\n- The second KRN: Wallet\
        \ API `account-pool`, which has the `spender` account\n- Just as in other\
        \ APIs, omitting the x-krn will give it the default value.<p></p>\n\n"
      operationId: TransferFromToken
      parameters:
      - name: x-chain-id
        in: header
        description: Klaytn Network Chain ID (1001 or 8217)
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: contract-address-or-alias
        in: path
        description: Contract address (in hexadecimal with the 0x prefix) or an alias
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/TransferKip7TokenFromRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Kip7TransactionStatusResponse'
              examples:
                Success:
                  summary: Success
                  value:
                    status: Submitted
                    transactionHash: 0x60412f876bfb8ae9953caa47be11cd5961a591198e09c25bb8cc3b26e416a862
                Success with multisig account:
                  summary: Success with multisig account
                  value:
                    status: Pending
                    transactionId: 0x947e5149c93e0bdbd3973e348a4b3557b857d2dee865f407b29f7f02c9b5d22e
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Bad Request - invalid address:
                  summary: Bad Request - invalid address
                  value:
                    code: 1134410
                    message: invalid address; to
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Not Found - alias:
                  summary: Alias not found
                  value:
                    code: 1134504
                    message: contract not found
  /v1/contract/{contract-address-or-alias}/account/{owner}/balance:
    get:
      tags:
      - KIP7
      summary: Get KIP-7 token balance
      description: "Shows the`{owner}`'s balance for the given KIP-7 contract.  <p></p>\n\
        \n"
      operationId: GetTokenBalance
      parameters:
      - name: x-chain-id
        in: header
        description: Klaytn Network Chain ID (1001 or 8217)
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: contract-address-or-alias
        in: path
        description: Contract address (in hexadecimal with the 0x prefix) or an alias
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: owner
        in: path
        description: Klaytn account address to query balance
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Kip7TokenBalanceResponse'
              examples:
                Success:
                  summary: Success
                  value:
                    balance: 0x10
                    decimals: 8
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Bad Request - invalid address:
                  summary: Bad Request - invalid address
                  value:
                    code: 1134410
                    message: invalid address; owner
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Not Found - alias:
                  summary: Alias not found
                  value:
                    code: 1134504
                    message: contract not found
  /v1/contract/{contract-address-or-alias}/approve:
    post:
      tags:
      - KIP7
      summary: Approve KIP-7 token transfer
      description: "Authorizes the `spender` to send a certain amount of tokens on\
        \ behalf of the `owner`. \nYou can execute a delegated token transfer by calling\
        \ [/v1/contract/{contract-address-or-alias}/transfer-from](#opera\tion/TransferFromToken)\
        \ API.<p></p>\n\n**Note**: Only a `spender` account address managed by Wallet\
        \ API can execute delegated token transfers.  <br>\n**Note**: This API requires\
        \ two types of x-krn, separated by `,` in the request header. <br>\nkrn:{chain-id}:kip7:{account-id}:account-pool:default,krn:{chain-id}:wallet:{account-id}:account-pool:{pool-name}<p></p>\n\
        \n- The first KRN: Default KIP-7 `account-pool`\n- The second KRN: `account-pool`\
        \ Wallet API, which has the `owner` account\n- Just as in other APIs, not\
        \ including the x-krn will give it the default value.<p></p>\n\n"
      operationId: ApproveToken
      parameters:
      - name: x-chain-id
        in: header
        description: Klaytn Network Chain ID (1001 or 8217)
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: contract-address-or-alias
        in: path
        description: Contract address (in hexadecimal with the 0x prefix) or an alias
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/ApproveKip7TokenRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Kip7TransactionStatusResponse'
              examples:
                Success:
                  summary: Success
                  value:
                    status: Submitted
                    transactionHash: 0x60412f876bfb8ae9953caa47be11cd5961a591198e09c25bb8cc3b26e416a862
                Success with multisig account:
                  summary: Success with multisig account
                  value:
                    status: Pending
                    transactionId: 0x947e5149c93e0bdbd3973e348a4b3557b857d2dee865f407b29f7f02c9b5d22e
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Bad Request - invalid address:
                  summary: Bad Request - invalid address
                  value:
                    code: 1130050
                    message: incorrect request; spender
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Not Found - alias:
                  summary: Alias not found
                  value:
                    code: 1134504
                    message: contract not found
  /v1/contract/{contract-address-or-alias}/account/{owner}/allowance/{spender}:
    get:
      tags:
      - KIP7
      summary: Returns the amount of approved KIP-7 tokens
      description: |+
        Shows the amount of tokens approved to the `spender` by the `owner`.<p></p>

      operationId: GetTokenAllowance
      parameters:
      - name: x-chain-id
        in: header
        description: Klaytn Network Chain ID (1001 or 8217)
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: contract-address-or-alias
        in: path
        description: Contract address (in hexadecimal with the 0x prefix) or an alias
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: owner
        in: path
        description: Token owner's Klaytn account address
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: spender
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Kip7TokenBalanceResponse'
              examples:
                Success:
                  summary: Success
                  value:
                    balance: 0x10
                    decimals: 8
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Bad Request - invalid address:
                  summary: Bad Request - invalid address
                  value:
                    code: 1134410
                    message: invalid address; owner
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Not Found - alias:
                  summary: Alias not found
                  value:
                    code: 1134504
                    message: contract not found
  /v1/contract/{contract-address-or-alias}/burn:
    delete:
      tags:
      - KIP7
      summary: Burn KIP-7 tokens
      description: "Burns tokens. The `totalSupply` on the contract will be deducted\
        \ accordingly.  <p></p>\n\n**Note**: This API requires two types of x-krn,\
        \ separated by `,` in the request header. <br>\nkrn:{chain-id}:kip7:{account-id}:account-pool:default,krn:{chain-id}:wallet:{account-id}:account-pool:{pool-name}<p></p>\n\
        \n- The first KRN: Default KIP-7 `account-pool`\n- The second KRN: Wallet\
        \ API `account-pool`, which has the `from` account\n- Just as in other APIs,\
        \ omitting the x-krn will give it the default value.<p></p>\n\n"
      operationId: BurnToken
      parameters:
      - name: x-chain-id
        in: header
        description: Klaytn Network Chain ID (1001 or 8217)
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: contract-address-or-alias
        in: path
        description: Contract address (in hexadecimal with the 0x prefix) or an alias
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/BurnKip7TokenRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Kip7TransactionStatusResponse'
              examples:
                Success:
                  summary: Success
                  value:
                    status: Submitted
                    transactionHash: 0x60412f876bfb8ae9953caa47be11cd5961a591198e09c25bb8cc3b26e416a862
                Success with multisig account:
                  summary: Success with multisig account
                  value:
                    status: Pending
                    transactionId: 0x947e5149c93e0bdbd3973e348a4b3557b857d2dee865f407b29f7f02c9b5d22e
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Bad Request - invalid amount:
                  summary: Bad Request - invalid amount
                  value:
                    code: 1134411
                    message: invalid amount; amount
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Not Found - alias:
                  summary: Alias not found
                  value:
                    code: 1134504
                    message: contract not found
  /v1/contract/{contract-address-or-alias}/burn-from:
    delete:
      tags:
      - KIP7
      summary: Burn approved KIP-7 tokens
      description: " `spender` burns `owner`'s tokens on the`owner`'s behalf. The\
        \ `totalSupply` on the contract will be deducted accordingly.  <p></p>\n\n\
        **Note**: This API requires two types of x-krn, separated by `,` in the request\
        \ header. <br>\nkrn:{chain-id}:kip7:{account-id}:account-pool:default,krn:{chain-id}:wallet:{account-id}:account-pool:{pool-name}<p></p>\n\
        \n- The first KRN: Default KIP-7 `account-pool`\n- The second KRN: `account-pool`\
        \ Wallet API, which has the `spender` account  \n- Just as in other APIs,\
        \ not including the x-krn will give it the default value.<p></p>\n\n"
      operationId: BurnFromToken
      parameters:
      - name: x-chain-id
        in: header
        description: Klaytn Network Chain ID (1001 or 8217)
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: contract-address-or-alias
        in: path
        description: Contract address (in hexadecimal with the 0x prefix) or an alias
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/BurnFromKip7TokenRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Kip7TransactionStatusResponse'
              examples:
                Success:
                  summary: Success
                  value:
                    status: Submitted
                    transactionHash: 0x60412f876bfb8ae9953caa47be11cd5961a591198e09c25bb8cc3b26e416a862
                Success with multisig account:
                  summary: Success with multisig account
                  value:
                    status: Pending
                    transactionId: 0x947e5149c93e0bdbd3973e348a4b3557b857d2dee865f407b29f7f02c9b5d22e
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Bad Request - invalid amount:
                  summary: Bad Request - invalid amount
                  value:
                    code: 1134410
                    message: invalid address; address
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Not Found - alias:
                  summary: Alias not found
                  value:
                    code: 1134504
                    message: contract not found
  /v1/deployer/default:
    get:
      tags:
      - KIP7Deployer
      summary: Retrieves the default contract deployer account
      description: "Queries the account that deploys and manages the KIP-7 contracts.\
        \ \n`deployer` will automatically be created during the initial contract deployment.<p></p>\n\
        \n"
      operationId: GetDefaultDeployer
      parameters:
      - name: x-chain-id
        in: header
        description: Klaytn Network Chain ID (1001 or 8217)
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Kip7DeployerResponse'
              examples:
                Success:
                  summary: Success
                  value:
                    address: 0xA490cbCB43a64cc4671F436dB9D33eD7A73Da675
                    krn: krn:1001:kip7:88c1223c-66af-4122-9818-069b2e3c6b30:account-pool:default
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Not Found:
                  summary: Not Found
                  value:
                    code: 1134506
                    message: deployer not found
components:
  schemas:
    Kip7ContractListResponse:
      title: Kip7ContractListResponse
      required:
      - cursor
      - items
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Kip7ContractListResponseItem'
        cursor:
          type: string
          description: Next page cursor
          example: ""
      description: ""
    ErrorResponse:
      title: ErrorResponse
      type: object
      properties:
        code:
          type: integer
          description: ""
          format: int64
          example: 1061010
        message:
          type: string
          description: ""
          example: data don't exist
        requestId:
          type: string
          description: ""
          example: 8b2219b0-ed0a-9247-a0ef-58d68f459cd2
      description: ""
    Kip7TransactionStatusResponse:
      title: Kip7TransactionStatusResponse
      required:
      - status
      type: object
      properties:
        status:
          type: string
          description: "Transaction status(`Submitted`,`Pending`)"
          example: Submitted
        transactionHash:
          type: string
          description: Transaction hash
          example: 0xf7843f034f2283d0ec32886a69d44a85ce19af25d8bd89d84322b973a86328a8
        transactionId:
          type: string
          description: Multisig transaction ID
          example: 0x947e5149c93e0bdbd3973e348a4b3557b857d2dee865f407b29f7f02c9b5d22e
      description: ""
    Kip7ContractMetadataResponse:
      title: Kip7ContractMetadataResponse
      required:
      - address
      - decimals
      - name
      - symbol
      - totalSupply
      type: object
      properties:
        address:
          type: string
          description: Contract address
          example: 0x0f73bb170deb398180f02e60d7ea154c270b8fb9
        decimals:
          type: integer
          description: Token decimal place
          format: int64
          example: 8
        name:
          type: string
          description: Contract name
          example: MyKIP7
        symbol:
          type: string
          description: Contract symbol
          example: MSK7
        totalSupply:
          type: string
          description: Total supply (in hexadecimal)
          example: 0x500
      description: ""
    Kip7TokenBalanceResponse:
      title: Kip7TokenBalanceResponse
      required:
      - balance
      - decimals
      type: object
      properties:
        balance:
          type: string
          description: Balance (in hexadecimal)
          example: 0x10
        decimals:
          type: integer
          description: Contract decimal place
          format: int64
          example: 8
      description: ""
    Kip7DeployerResponse:
      title: Kip7DeployerResponse
      required:
      - address
      - krn
      type: object
      properties:
        address:
          type: string
          description: Default Klaytn account address that manages the contracts
          example: 0xA490cbCB43a64cc4671F436dB9D33eD7A73Da675
        krn:
          type: string
          description: KRN of the account
          example: krn:1001:kip7:88c1223c-66af-4122-9818-069b2e3c6b30:account-pool:default
      description: ""
    DeployKip7ContractRequest:
      title: DeployKip7ContractRequest
      required:
      - alias
      - initialSupply
      - name
      - symbol
      type: object
      properties:
        alias:
          type: string
          description: "Contract alias; for KIP-7 API, you can use not only the contract\
            \ address but also an alias."
          example: mycontract
        name:
          type: string
          description: Contract name
          example: MyKIP7
        symbol:
          type: string
          description: Token symbol
          example: MSK7
        decimals:
          type: integer
          description: Token decimal place. The default value is `0`.
          format: int64
          example: 8
        initialSupply:
          type: string
          description: Initial supply (in hexadecimal)
          example: 0x100
      description: ""
    MintKip7TokenRequest:
      title: MintKip7TokenRequest
      required:
      - amount
      - to
      type: object
      properties:
        to:
          type: string
          description: Klaytn account address to receive the newly created token
          example: not-eoa
        amount:
          type: string
          description: The amount of tokens to create (in hexadecimal)
          example: 0x10
      description: ""
    TransferKip7TokenRequest:
      title: TransferKip7TokenRequest
      required:
      - amount
      - to
      type: object
      properties:
        from:
          type: string
          description: Klaytn account address to send tokens. The default value is
            the contract deployer account.
          example: 0xd6905b98E4Ba43a24E842d2b66c1410173791cab
        to:
          type: string
          description: Klaytn account address to receive tokens
          example: 0xaddbf9cbfd30768202b70b5504c012fbdf00b8d8
        amount:
          type: string
          description: The amount of tokens to transfer (in hexadecimal)
          example: 0x50
      description: ""
    TransferKip7TokenFromRequest:
      title: TransferKip7TokenFromRequest
      required:
      - amount
      - owner
      - spender
      - to
      type: object
      properties:
        spender:
          type: string
          description: Klaytn account address to send tokens
          example: 0xd6905b98E4Ba43a24E842d2b66c1410173791cab
        owner:
          type: string
          description: Klaytn account address of the owner delegating the token transfer
          example: 0x1eb15b3ccb2add3bfe132a4f6ad21ca62cf94e6d
        to:
          type: string
          description: Klaytn account address to receive tokens
          example: not-eoa
        amount:
          type: string
          description: Transfer amount (in hexadecimal)
          example: 0x50
      description: ""
    ApproveKip7TokenRequest:
      title: ApproveKip7TokenRequest
      required:
      - amount
      - spender
      type: object
      properties:
        owner:
          type: string
          description: Klaytn account address of the owner delegating the token tranfer.
            The default is the contract deployer account.
          example: 0x1eb15b3ccb2add3bfe132a4f6ad21ca62cf94e6d
        spender:
          type: string
          description: Klaytn account address to approve delegated token transfer
          example: 0xfb7ead209e113ff15f588852f112cf331d02b4bf
        amount:
          type: string
          description: Approved token amount (in hexadecimal)
          example: 0x5c2
      description: ""
    BurnKip7TokenRequest:
      title: BurnKip7TokenRequest
      required:
      - amount
      type: object
      properties:
        from:
          type: string
          description: Klaytn account address on which the tokens will be burned.
            The default value is the contract deployer account.
          example: 0x1eb15b3ccb2add3bfe132a4f6ad21ca62cf94e6d
        amount:
          type: string
          description: The amount of tokens to burn (in hexadecimal)
          example: not hex string
      description: ""
    BurnFromKip7TokenRequest:
      title: BurnFromKip7TokenRequest
      required:
      - amount
      - owner
      - spender
      type: object
      properties:
        owner:
          type: string
          description: Klaytn account address of the owner of the tokens to be burned
          example: 0x1eb15b3ccb2add3bfe132a4f6ad21ca62cf94e6d
        spender:
          type: string
          description: Klaytn account address on which the tokens will be burned
          example: not-eoa
        amount:
          type: string
          description: The amount of tokens to burn (in hexadecimal)
          example: 0x100
      description: ""
    Kip7ContractListResponseItem:
      title: Kip7ContractListResponseItem
      required:
      - address
      - alias
      - decimals
      - name
      - status
      - symbol
      - totalSupply
      type: object
      properties:
        address:
          type: string
          description: Contract address
          example: 0x0f73bb170deb398180f02e60d7ea154c270b8fb9
        alias:
          type: string
          description: Contract alias
          example: mycontract
        decimals:
          type: integer
          description: Token decimal place
          format: int64
          example: 8
        name:
          type: string
          description: Contract name
          example: MyKIP7
        status:
          type: string
          description: "Contract deploy status[`init`,`submitted`,`deployed`]"
          example: deployed
        symbol:
          type: string
          description: Contract symbol
          example: MSK7
        totalSupply:
          type: string
          description: Total supply (in hexadecimal)
          example: 0x500
      description: ""
  requestBodies:
    DeployKip7ContractRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DeployKip7ContractRequest'
          examples:
            Success:
              value:
                alias: mycontract
                name: MyKIP7
                symbol: MSK7
                decimals: 8
                initialSupply: 0x100
            Duplicate Alias:
              value:
                alias: mycontract
                name: MyKIP7
                symbol: MSK7
                decimals: 8
                initialSupply: 0x100
    MintKip7TokenRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MintKip7TokenRequest'
          examples:
            Bad Request - invalid address:
              value:
                to: not-eoa
                amount: 0x10
            Not found - alias:
              value:
                to: 0xd6905b98E4Ba43a24E842d2b66c1410173791cab
                amount: 0x10
            Success:
              value:
                to: 0xd6905b98E4Ba43a24E842d2b66c1410173791cab
                amount: 0x10
    TransferKip7TokenRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TransferKip7TokenRequest'
          examples:
            Success:
              value:
                from: 0xd6905b98E4Ba43a24E842d2b66c1410173791cab
                to: 0xaddbf9cbfd30768202b70b5504c012fbdf00b8d8
                amount: 0x50
            Bad Request - invalid address:
              value:
                from: 0xd6905b98E4Ba43a24E842d2b66c1410173791cab
                to: not-eoa
                amount: 0x10
            Not Found - alias:
              value:
                from: 0xd6905b98E4Ba43a24E842d2b66c1410173791cab
                to: 0xd6905b98E4Ba43a24E842d2b66c1410173791cab
                amount: 0x10
    TransferKip7TokenFromRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TransferKip7TokenFromRequest'
          examples:
            Bad Request - invalid address:
              value:
                spender: 0xd6905b98E4Ba43a24E842d2b66c1410173791cab
                owner: 0x1eb15b3ccb2add3bfe132a4f6ad21ca62cf94e6d
                to: not-eoa
                amount: 0x50
            Not Found - alias:
              value:
                spender: 0xd6905b98E4Ba43a24E842d2b66c1410173791cab
                owner: 0x1eb15b3ccb2add3bfe132a4f6ad21ca62cf94e6d
                to: 0xaddbf9cbfd30768202b70b5504c012fbdf00b8d8
                amount: 0x50
            Success:
              value:
                spender: 0xd6905b98E4Ba43a24E842d2b66c1410173791cab
                owner: 0x1eb15b3ccb2add3bfe132a4f6ad21ca62cf94e6d
                to: 0xaddbf9cbfd30768202b70b5504c012fbdf00b8d8
                amount: 0x50
    ApproveKip7TokenRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApproveKip7TokenRequest'
          examples:
            Success:
              value:
                owner: 0x1eb15b3ccb2add3bfe132a4f6ad21ca62cf94e6d
                spender: 0xfb7ead209e113ff15f588852f112cf331d02b4bf
                amount: 0x5c2
            Not Found - alias:
              value:
                owner: 0x1eb15b3ccb2add3bfe132a4f6ad21ca62cf94e6d
                spender: 0xfb7ead209e113ff15f588852f112cf331d02b4bf
                amount: 0x5c2
            Bad Request - invalid address:
              value:
                owner: 0x1eb15b3ccb2add3bfe132a4f6ad21ca62cf94e6d
                spender: not-eoa
                amount: 0x5c2
    BurnKip7TokenRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BurnKip7TokenRequest'
          examples:
            Bad Request - invalid amount:
              value:
                from: 0x1eb15b3ccb2add3bfe132a4f6ad21ca62cf94e6d
                amount: not hex string
            Not Found - alias:
              value:
                from: 0x1eb15b3ccb2add3bfe132a4f6ad21ca62cf94e6d
                amount: 0x5c2
            Success:
              value:
                from: 0x1eb15b3ccb2add3bfe132a4f6ad21ca62cf94e6d
                amount: 0x100
    BurnFromKip7TokenRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BurnFromKip7TokenRequest'
          examples:
            Bad Request - invalid amount:
              value:
                owner: 0x1eb15b3ccb2add3bfe132a4f6ad21ca62cf94e6d
                spender: not-eoa
                amount: 0x100
            Success:
              value:
                owner: 0x1eb15b3ccb2add3bfe132a4f6ad21ca62cf94e6d
                spender: 0x08c7a5d79f37f658f2dd30da0af02fdfd0cb773e
                amount: 0x100
            Not Found - alias:
              value:
                owner: 0x1eb15b3ccb2add3bfe132a4f6ad21ca62cf94e6d
                spender: 0x08c7a5d79f37f658f2dd30da0af02fdfd0cb773e
                amount: 0x100
  securitySchemes:
    basic:
      type: http
      description: "KAS uses Basic HTTP Auth. All requests must have a correct Authorization\
        \ header and a KAS user can create the credentials to be used for Basic Auth\
        \ by using `username` as access key ID and `password` as secret access key.\n\
        \nAll credentials on KAS enable full access to KAS and to the Klaytn account\
        \ created with the Wallet API. It authorizes asset transfers of Klaytn account's\
        \ assets (like KLAY) as well as [Transaction Execution](https://docs.klaytnapi.com/tutorial/wallet-transaction-api).\
        \ To keep your KAS/Klaytn accounts secure, do not share your KAS API Secret\
        \ Access Key with others.\n### cURL\n```\n  curl --location --request GET\
        \ 'https://kip7-api.klaytnapi.com/v1/contract' \\\n  -u ${your_accessKeyId}:${your_secretAccessKey}\
        \ \\\n  --header 'x-chain-id: 1001' \\\n  --header 'Content-Type: application/json'\n\
        ```      \n\n"
      scheme: basic
