openapi: 3.0.0
info:
  title: Anchor API
  description: >
    # Introduction

    이 문서는 KAS\(Klaytn API Service\)의 Anchor API를 소개하는 문서입니다. Anchor API는 서비스 체인
    데이터의 신뢰성을 보장하기 위해 데이터 신뢰성을 증명할 수 있는 메타데이터를 Klaytn 메인 체인에 전송하는 기능을 제공합니다.


    자세한 사용 예시는 [튜토리얼](링크)를 확인하십시오.




    # Error Codes


    ## 400: Bad Request

     | Code | Messages | 
     | --- | --- | 
     | 1071010 | data don't exist
    1071615 | its value is out of range; size

    1072100 | same payload ID or payload was already anchored

    1072101 | all configured accounts have insufficient funds | 
paths:
  /v1/anchor:
    post:
      description: >-
        블록체인 데이터를 앵커링 하기 위해 사용됩니다. 이미 설정한 오퍼레이터를 통해 앵커 트랜잭션 발생 및 관리합니다.

        오퍼레이터 또는 사용자 Feepayer 를 통한 앵커링을 성공하기 위해서는 실제 요구되는 수수료의 10배이상 잔액을 보유하여야
        합니다.
      parameters:
        - description: Klaytn 체인 네트워크 ID (1001 or 8217)
          in: header
          name: x-chain-id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              examples:
                200 - Success:
                  summary: 200 - Success
                  description: ''
                  value:
                    status: succeed
              schema:
                $ref: '#/components/schemas/AnchorBlockStatus'
        '400':
          description: ''
          content:
            application/json:
              examples:
                400 - Insufficient funds:
                  summary: 400 - Insufficient funds
                  description: ''
                  value:
                    code: 1072101
                    message: all configured accounts have insufficient funds
                400 - Duplicated payload:
                  summary: 400 - Duplicated payload
                  description: ''
                  value:
                    code: 1072100
                    message: same payload ID or payload was already anchored
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      summary: 앵커링 트랜잭션 생성
      operationId: AnchorBlock
      tags:
        - Data Anchoring Transaction
      requestBody:
        $ref: '#/components/requestBodies/AnchorBlockRequest'
  '/v1/operator/{operator-id}/tx':
    get:
      description: |-
        오퍼레이터 ID를 지정하여, 이 오퍼레이터가 생성한 트랜잭션 목록을 조회합니다.

        ## Size

        * `size` 쿼리 파라미터는 선택 파라미터입니다 (최소값 = 1, 최대값 = 1000, 기본값 = 100)
        * 음수를 입력하면 오류를 반환합니다
        * 0을 입력하면 기본값(`size=100`)을 사용합니다
        * 최대값보다 큰 값을 입력하면 최대값을 사용합니다
      parameters:
        - description: Klaytn 체인 네트워크 ID (1001 or 8217)
          in: header
          name: x-chain-id
          required: true
          schema:
            type: string
        - description: 검색할 계정의 최대 사이즈
          in: query
          name: size
          required: false
          schema:
            type: integer
            format: int64
            maximum: 1000
            default: 100
          example: 100
        - description: 마지막으로 검색된 커서의 정보
          in: query
          name: cursor
          required: false
          schema:
            type: string
          example: ''
        - description: 검색하고자 하는 처음 시간의 타임스탬프 (초단위)
          in: query
          name: from-timestamp
          required: false
          schema:
            type: integer
            format: int64
        - description: 검색하고자 하는 마지막 시간의 타임스탬프 (초단위)
          in: query
          name: to-timestamp
          required: false
          schema:
            type: integer
            format: int64
        - description: 오퍼레이터 계정 주소
          in: path
          name: operator-id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              examples:
                200 - Success:
                  summary: 200 - Success
                  description: ''
                  value:
                    cursor: ''
                    items:
                      - createdAt: 1599142860
                        payloadId: c61cc0d0-5878-450e-bec8-bf73d6184798
                        transactionHash: >-
                          0x5aeb4ddc5d77b9ce977a87461573da00c0aed0ac59962892ecf58ec09296e79d
                      - createdAt: 1599142859
                        payloadId: d4f1a11f-4609-40f5-9d59-2313a5799508
                        transactionHash: >-
                          0x70f6f6745ad0b0f4ce5908f40d20a1f44bd34871e0428be782d84f9a53ea2ba0
                      - createdAt: 1599142857
                        payloadId: 48b59825-82b2-4595-abfb-c465112618cc
                        transactionHash: >-
                          0x3f90cd2e02576fd85572ab76aff49b87b9cf3efb623f34bb8d6354ee1b88869f
                      - createdAt: 1599142841
                        payloadId: b315de34-52cb-41c0-9383-3260ceafd3b2
                        transactionHash: >-
                          0x8a73a00f04a1f6e8d8af101487bd35f8dbcce6fcb3ddd95059f42b8f7fbc3345
              schema:
                $ref: '#/components/schemas/AnchorTransactions'
        '400':
          description: ''
          content:
            application/json:
              examples:
                400 - Out of Range:
                  summary: 400 - Out of Range
                  description: ''
                  value:
                    code: 1071615
                    message: its value is out of range; size
                400 - No content:
                  summary: 400 - No content
                  description: ''
                  value:
                    code: 1071010
                    message: data don't exist
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      summary: 오퍼레이터로 앵커링 트랜잭션 목록 조회
      operationId: RetrieveAnchorBlock
      tags:
        - Data Anchoring Transaction
  '/v1/operator/{operator-id}/tx/{transaction-hash}':
    get:
      description: >-
        트랜잭션 해시값과 오퍼레이터 ID를 지정하여, 이 오퍼레이터가 생성한 트랜잭션을 조회합니다. 트랜잭션을 일으킬 때 트랜잭션에
        덧붙인 Payload를 살펴볼 수 있습니다.
      parameters:
        - description: Klaytn 체인 네트워크 ID (1001 or 8217)
          in: header
          name: x-chain-id
          required: true
          schema:
            type: string
        - description: 오퍼레이터 계정 주소
          in: path
          name: operator-id
          required: true
          schema:
            type: string
        - description: 트랜잭션 해시
          in: path
          name: transaction-hash
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              examples:
                200 - Success:
                  summary: 200 - Success
                  description: ''
                  value:
                    payload:
                      custom_field1: field1
                      custom_field2: field2
                      id: c61cc0d0-5878-450e-bec8-bf73d6184798
                    transactionHash: >-
                      0x5aeb4ddc5d77b9ce977a87461573da00c0aed0ac59962892ecf58ec09296e79d
              schema:
                $ref: '#/components/schemas/AnchorTransactionDetail'
        '400':
          description: ''
          content:
            application/json:
              examples:
                400 - No content:
                  summary: 400 - No content
                  description: ''
                  value:
                    code: 1071010
                    message: data don't exist
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      summary: 트랜잭션 해시로 앵커링 트랜잭션 조회
      operationId: GetAnchorBlockByTx
      tags:
        - Data Anchoring Transaction
  '/v1/operator/{operator-id}/payload/{payload-id}':
    get:
      description: >-
        Paylaod ID와 오퍼레이터 ID를 지정하여, 이 오퍼레이터가 생성한 트랜잭션을 조회합니다. 트랜잭션을 일으킬 때 트랜잭션에
        덧붙인 Payload를 살펴볼 수 있습니다.
      parameters:
        - description: Klaytn 체인 네트워크 ID (1001 or 8217)
          in: header
          name: x-chain-id
          required: true
          schema:
            type: string
        - description: 오퍼레이터 계정 주소
          in: path
          name: operator-id
          required: true
          schema:
            type: string
        - description: 페이로드 ID
          in: path
          name: payload-id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              examples:
                200 - Success:
                  summary: 200 - Success
                  description: ''
                  value:
                    payload:
                      custom_field1: field1
                      custom_field2: field2
                      id: c61cc0d0-5878-450e-bec8-bf73d6184798
                    transactionHash: >-
                      0x5aeb4ddc5d77b9ce977a87461573da00c0aed0ac59962892ecf58ec09296e79d
              schema:
                $ref: '#/components/schemas/AnchorTransactionDetail'
        '400':
          description: ''
          content:
            application/json:
              examples:
                400 - No content:
                  summary: 400 - No content
                  description: ''
                  value:
                    code: 1071010
                    message: data don't exist
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      summary: 페이로드로 앵커링 트랜잭션 조회
      operationId: GetAnchorBlockByPayloadID
      tags:
        - Data Anchoring Transaction
  /v1/operator:
    get:
      description: |-
        이미 생성된 오퍼레이터 목록 및 각 오퍼레이터 설정값을 조회합니다.

        ## Size

        * `size` 쿼리 파라미터는 선택 파라미터입니다 (최소값 = 1, 최대값 = 1000, 기본값 = 100)
        * 음수를 입력하면 오류를 반환합니다
        * 0을 입력하면 기본값(`size=100`)을 사용합니다
        * 최대값보다 큰 값을 입력하면 최대값을 사용합니다
      parameters:
        - description: Klaytn 체인 네트워크 ID (1001 or 8217)
          in: header
          name: x-chain-id
          required: true
          schema:
            type: string
        - description: 검색할 계정의 최대 사이즈
          in: query
          name: size
          required: false
          schema:
            type: integer
            format: int64
            maximum: 1000
            default: 100
          example: 10
        - description: 마지막으로 검색된 커서의 정보
          in: query
          name: cursor
          required: false
          schema:
            type: string
          example: ''
        - description: 검색하고자 하는 처음 시간의 타임스탬프 (초단위)
          in: query
          name: from-timestamp
          required: false
          schema:
            type: integer
            format: int64
        - description: 검색하고자 하는 마지막 시간의 타임스탬프 (초단위)
          in: query
          name: to-timestamp
          required: false
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: ''
          content:
            application/json:
              examples:
                200 - Success:
                  summary: 200 - Success
                  description: ''
                  value:
                    cursor: ''
                    items:
                      - createdAt: 1600156363
                        operator: '0x36C144b998FbEF7faf092b01815194a18e1a1163'
                        setting:
                          useGlobalFeePayer: true
                          useOperator: true
                      - createdAt: 1600156362
                        operator: '0xfD522BE38Ae3Ec4F84A7A411A9e2b3Aee81317b5'
                        setting:
                          useGlobalFeePayer: true
                          useOperator: true
                      - createdAt: 1600156361
                        operator: '0xA54579E74e4709600AA7fb91D4cfefb1aECFF9ee'
                        setting:
                          useGlobalFeePayer: true
                          useOperator: true
                      - createdAt: 1600156360
                        operator: '0xBBe7d40917d99eF1581b3abc7cdA69492C860F1F'
                        setting:
                          useGlobalFeePayer: true
                          useOperator: true
                      - createdAt: 1600156359
                        operator: '0xc72408058DAC1343B8C99Ca90Cb58Ea89637C1eE'
                        setting:
                          useGlobalFeePayer: true
                          useOperator: true
                      - createdAt: 1600156351
                        operator: '0x8f315315F90B0b3dEA038FC659F07bac62Fcb2f6'
                        setting:
                          useGlobalFeePayer: true
                          useOperator: true
              schema:
                $ref: '#/components/schemas/Operators'
        '400':
          description: ''
          content:
            application/json:
              examples:
                400 - Out of Range:
                  summary: 400 - Out of Range
                  description: ''
                  value:
                    code: 1071615
                    message: its value is out of range; size
                400 - No content:
                  summary: 400 - No content
                  description: ''
                  value:
                    code: 1071010
                    message: data don't exist
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      summary: 모든 오퍼레이터 목록 조회
      operationId: RetrieveOperators
      tags:
        - Operator
  '/v1/operator/{operator-id}':
    get:
      description: 해당 오퍼레이터 설정 및 오퍼레이터 계정 잔액을 조회합니다.
      parameters:
        - description: Klaytn 체인 네트워크 ID (1001 or 8217)
          in: header
          name: x-chain-id
          required: true
          schema:
            type: string
        - description: 오퍼레이터 계정 주소
          in: path
          name: operator-id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              examples:
                200 - Success:
                  summary: 200 - Success
                  description: ''
                  value:
                    operator: '0x6945B46Add33ABD0576b4D99B4c86Fe28c0Ad026'
                    setting:
                      useGlobalFeePayer: true
                      useOperator: true
              schema:
                $ref: '#/components/schemas/Operator'
      summary: 특정 오퍼레이터 조회
      operationId: GetOperator
      tags:
        - Operator
tags: []
servers:
  - url: 'https://anchor-api.klaytnapi.com'
components:
  schemas:
    AnchorBlockStatus:
      type: object
      description: 앵커링 상태 응답
      properties:
        status:
          type: string
          example: succeed
          description: 앵커링 성공 여부
      title: AnchorBlockStatus
      required:
        - status
    ErrorResponse:
      type: object
      description: 에러에 대한 설명을 포함한 응답
      properties:
        code:
          type: integer
          format: int64
          example: 1072101
          description: 서비스 코드(앞 3자리)와 에러 코드(뒤 4자리)
        message:
          type: string
          example: all configured accounts have insufficient funds
          description: 에러 메세지
      title: ErrorResponse
      required:
        - code
        - message
    AnchorBlockRequest:
      type: object
      description: 앵커 블록 요청 스키마
      properties:
        operator:
          type: string
          example: '0x426Cd8fF0672225c7e96E0bD2f9175B05790653d'
          description: 오퍼레이터 계정 주소
        payload:
          $ref: '#/components/schemas/AnchorBlockPayload'
      title: AnchorBlockRequest
      required:
        - operator
        - payload
    AnchorBlockPayload:
      type: object
      description: >-
        앵커 데이터. ID 를 설정하지 않는 경우에는 기본적으로 id = SHA256(payload)로 설정됨. string 타입의 id
        값을 받으며 string 타입이 아닌 경우 설정하지 않은 것으로 판단함.
      title: AnchorBlockPayload
      additionalProperties: {}
    AnchorTransactions:
      type: object
      description: 앵커링 트랜잭션 목록
      properties:
        cursor:
          type: string
          example: ''
          description: 마지막 검색 위치를 나타내는 커서 정보
        items:
          type: array
          items:
            $ref: '#/components/schemas/AnchorTransaction'
      title: AnchorTransactions
      required:
        - cursor
    AnchorTransaction:
      type: object
      description: 앵커링 트랜잭션 정보
      properties:
        createdAt:
          type: integer
          format: int64
          example: 1599142860
          description: 앵커링 트랜잭션 생성 시간
        payloadId:
          type: string
          example: c61cc0d0-5878-450e-bec8-bf73d6184798
          description: 페이로드 ID
        transactionHash:
          type: string
          example: '0x5aeb4ddc5d77b9ce977a87461573da00c0aed0ac59962892ecf58ec09296e79d'
          description: 앵커링 트랜잭션의 트랜잭션 해시
      title: AnchorTransaction
      required:
        - createdAt
        - payloadId
        - transactionHash
    AnchorTransactionDetail:
      type: object
      description: 앵커링 트랜잭션 정보
      properties:
        payload:
          $ref: '#/components/schemas/AnchorBlockPayload'
        transactionHash:
          type: string
          example: '0x5aeb4ddc5d77b9ce977a87461573da00c0aed0ac59962892ecf58ec09296e79d'
          description: 앵커링 트랜잭션의 트랜잭션 해시
      title: AnchorTransactionDetail
      required:
        - payload
        - transactionHash
    Operators:
      type: object
      description: 오퍼레이터 목록
      properties:
        cursor:
          type: string
          example: ''
          description: 마지막 검색 위치를 나타내는 커서 정보
        items:
          type: array
          items:
            $ref: '#/components/schemas/Operator'
      title: Operators
      required:
        - cursor
    Operator:
      type: object
      description: 오퍼레이터 정보
      properties:
        createdAt:
          type: integer
          format: int64
          example: 1600156363
          description: 오퍼레이터 생성 시간
        operator:
          type: string
          example: '0x36C144b998FbEF7faf092b01815194a18e1a1163'
          description: 오퍼레이터 클레이튼 계정 주소
        setting:
          $ref: '#/components/schemas/OperatorSetting'
      title: Operator
      required:
        - createdAt
        - operator
    OperatorSetting:
      type: object
      description: 오퍼레이터 결제 정보
      properties:
        useGlobalFeePayer:
          type: boolean
          example: true
          description: 글로벌 대납 계정 사용 여부
        useOperator:
          type: boolean
          example: true
          description: 오퍼레이터 결제 사용 여부
      title: OperatorSetting
      required:
        - useGlobalFeePayer
        - useOperator
  securitySchemes:
    basic:
      description: >+
        KAS는 Basic HTTP Auth를 사용합니다. 모든 요청은 반드시 올바른 Authorization 헤더를 가져야 하며 KAS
        사용자는 access key ID를 `username`으로, secret access key를 `password`로 사용하여
        Basic Auth에 사용할 자격증명을 생성합니다.

        ### cURL

        ```
          curl --location --request GET 'https://https://anchor-api.klaytnapi.com/v1/operator/:operator-id/tx' \
          -u ${your_accessKeyId}:${your_secretAccessKey} \
          --header 'x-chain-id: {{chain-id}}' \
          --header 'Content-Type: application/json'
        ```      

      type: http
      scheme: basic
  requestBodies:
    AnchorBlockRequest:
      content:
        application/json:
          examples:
            200 - Success:
              value:
                operator: '0x426Cd8fF0672225c7e96E0bD2f9175B05790653d'
                payload:
                  id: unique_custom_id
                  custom_field1: field1
                  custom_field2: field2
            400 - Insufficient funds:
              value:
                operator: '0x84ddfb88a28de014d5fea114dc1efb06ce99cc42'
                payload:
                  id: custom_id
                  custom_field1: field1
                  custom_field2: field2
            400 - Duplicated payload:
              value:
                operator: '0x426Cd8fF0672225c7e96E0bD2f9175B05790653d'
                payload:
                  id: custom_id
                  custom_field1: field1
                  custom_field2: field2
          schema:
            $ref: '#/components/schemas/AnchorBlockRequest'
security:
  - basic: []
